name: "DokuWiki"
description: "A fast and light wiki for your Home Assistant documentation"
version: "1.0.0"
slug: "dokuwiki"
init: false
startup: application
arch:
  - aarch64
  - amd64
ingress: true
ingress_port: 8080
panel_icon: mdi:book-open-page-variant
map:
  - share:rw
host_network: false
options: {}
schema: {}
